### ISSUE TITLE
cloudfront url

### ISSUE THREAD

**Issue by stloc** [brefphp/bref#1134]
**Description:**

In symfony application (with easyadmin bundle) I can't set cloudfront url on links. Relatives URL take AWS default endpoint instead xxxx.execute-api.eu-west-3.amazonaws.com

**How to reproduce:**

![image](https://user-images.githubusercontent.com/4832070/148205250-9e4ea3eb-812f-41cf-aa4f-b3d86d896b73.png)

**Comment by t-richard** [comment]
This is probably because you don't trust the `x-forwarded-host` header, please see https://bref.sh/docs/frameworks/symfony.html#trust-api-gateway

NB: for this to work, your cloudfront distribution must set this header. This is done automatically when using the Lift plugin for serverless framework

**Comment by stloc** [comment]
I had followed this advice without success

**Comment by stloc** [comment]
yes

**Comment by t-richard** [comment]
This issue is generally linked to Symfony not using the correct host and is solved with making symfony use the `x-forwarded-host` as the source of truth. Maybe the header is not set in the request Symfony is receiving for some reason. Maybe you could try to log/dump this header to see if it's present and has the correct value.

I actually can't think of another reason this is happening. I've been running in a similar setup without issues.

If you were able to share a reproducer for this issue, I'd happily look into it.

**Comment by stloc** [comment]
I have found the solution : a parameter to change on bundle easyadmin. There is an option https://symfony.com/bundles/EasyAdminBundle/current/dashboards.html#dashboard-configuration `->generateRelativeUrls()` else that generate a wrong absolute URL
