### ISSUE TITLE
Add support for AWS GovCloud

### ISSUE THREAD

**Issue by norndorff** [brefphp/bref#1275]
Currently the AWS GovCloud regions do not appear to be supported: https://runtimes.bref.sh

This request is to add support for the GovCloud regions (us-gov-west-1 and us-gov-east-1).

**Comment by t-richard** [comment]
Thanks for your interest in Bref!

To make Bref available in a given region, the main Bref account needs access to that region so that we can push the Bref Lambda layers to that region.

Unfortunately, Gov Cloud has restrictive access conditions

> AWS GovCloud (US) requires a separate account ID and user access credentials in addition to those required for an associated standard AWS account. Access is restricted to customers who are U.S. persons, not subject to export restrictions, and who comply with US export control laws and regulations, including the International Traffic in Arms Regulations (ITAR).

The main problem here is "customers who are US persons". Bref maintainers are not US citizens so we can't have access to those regions. 

And because Gov Cloud is meant to comply with strict US regulations, I'm not sure there's a way to work around that. 

However, you can build and deploy Bref layers yourself to your aws account in the Gov Cloud regions.

**Comment by norndorff** [comment]
Thanks @t-richard. That makes sense- I didn't think of the restrictions placed on the maintainers. 

I did start down the path of deploying Bref layers myself so I'll continue with that and close this issue. Thanks again!
