### ISSUE TITLE
Get rid of `separateVendor: true` for Bref v2

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#1318]
I am considering removing the `separateVendor: true` feature for Bref 2.0 (https://bref.sh/docs/environment/php.html#separate-vendor-folder).

Motivation:

- this feature was contributed a while ago but it's never been maintained, it adds a lot of technical debt and bugs (e.g. last one is #1311)
- I'm not sure it is used a lot
- I'd actually recommend deploying using Docker images instead, as this provides flat cold starts (better performances)

Any opinions here? Anyone using it?

**Comment by liepumartins** [comment]
I would say it is not necessary, especially if it slows the whole thing down.

I am still playing around with both bref/serverless and Laravel Vapor.
I had to use `separateVendor: true` otherwise it died with memory error. However playing also with Vapor left me 2 choices - reduce vendor directory or use Docker which I was reluctant to do.
Investigated further, turns out I had a package that ships whole GeoLite database along adding about 50 megs (about 30% of whole vendor dir) I ditched it and Vapor was happy to pack it.

There is also the huge aws package that adds about 35 megs (https://github.com/aws/aws-sdk-php/issues/808), everything else is reasonably sized and does not create any trouble.

```
$ du -h -d 1 vendor/ | sort -h
# lots of small packages
...
7.9M    vendor/symfony
13M     vendor/laravel
37M     vendor/aws
103M    vendor/
```

**Comment by brighttank** [comment]
I tried using it as it allows functions to be updated individually but kept getting 502 errors in production. Didn't have the bandwidth to debug the core issue so I abandoned the idea. I would agree that it it's just adding bugs then it's best not to have it.

**Comment by deleugpn** [comment]
I have used Docker for packing a 800MB project into Lambda and I am in favor of that approach over vendor separation.
