### ISSUE TITLE
On php-fpm layer in production,   after a certain limit,  logging on stderr  hang the process

### ISSUE THREAD

**Issue by allan-simon** [brefphp/bref#1369]
**Description:**

I'm not sure if it's a bref bug or a AWS one but writting too much log on stderr hang after an arbitrary limit  

something like  "you write 152 logs, it's fine"  " you try to write the 153th, it timeout" 

**How to reproduce:**

I created this route to reproduce the issue 

```
    #[Route(
        path: '/test-reproduce-bref-issue',
        name: 'ping',
        methods: ['GET', 'HEAD']
    )]
    public function brefIssueReproducer(LoggerInterface $logger, Request $request): JsonResponse
    {
        for ($i = 0; $i < $request->query->getInt('nbrLog'); $i++) {
            $logger->info("you_can_ignore_i_m_just_here_to_try_to_reproduce_a_bug");
        }
        return $this->json([]);
    }

```

That you can test live here 

https://app-testenv.rosaly.info/test-reproduce-bref-issue?nbrLog=153  -> does not hang , quite fast 99ms 
https://app-testenv.rosaly.info/test-reproduce-bref-issue?nbrLog=154 ->  hang , timeout (we have 15 seconds timeout)

**Comment by StephaneLeveugle** [comment]
Hi,

I just wanted to say I encountered the same issue.
It can also be reproduced by writing a huge log (like 150k characters).

**Comment by mnapoli** [comment]
🤔 interesting, this comes to mind: 

https://github.com/brefphp/bref/blob/eea8884dc20510bed70d618bc0b67c9be2727bd0/runtime/layers/fpm/php-fpm.conf#L9-L10

> Log limit for the logged lines which allows to log messages longer than 1024 characters without wrapping. Default value: 1024. Available as of PHP 7.3.0. 

Your sentence contains 54 characters. 154*54 is 8316, which is weirdly close to that number 🤔

But maybe this is a red herring…

**Comment by allan-simon** [comment]
to be honest I second @StephaneLeveugle  ,  that number was different with the initial log I had in production. 


but yes may be not that directly linked to this property, because our log are json-formatted, so they take actually much more place on stderr

**Comment by allan-simon** [comment]
Also I can't reproduce it with  the image `bref/php-81-fpm-dev`

**Comment by allan-simon** [comment]
I've just found this issue https://github.com/php/php-src/issues/9010  

so I will propose as here  https://github.com/php/php-src/issues/9010#issuecomment-1184680406  a PR to set the limit to the limit of  AWS cloudwatch

**Comment by mnapoli** [comment]
oh interesting!

**Comment by alexw23** [comment]
Noticing the same bug, if I write logs to a file it works fine, if I write to stderr it intermittently freezes up in local development.

**Comment by driskell** [comment]
I looked at the code and I think issue is that the PHP-FPM is started using Symfony Process which doesn’t support forwarding descriptors - so indeed what happens is a pipe is opened between PHP running the runtime and PHP-FPM.

The only time that Symfony Process will read the pipes is when waiting or as part of checking the status. However once Bref sends a request to PHP-FPM over the socket it then blocks waiting for the FPM response for the request because the FastCgi socket processing is also blocking. So if the pipe fills up you could have PHP-FPM blocking on writing to STDERR waiting for it to be read from and PHP blocking on reading from the socket waiting for it to be written to, and so deadlock.

Probably best is for proc_open to be used directly to forward the STDOUT and STDERR descriptor directly. In a way it’s probably just as easy as most of Symfony Process is unneeded here and none of the Windows compat? Worth a test I think.

**Comment by allan-simon** [comment]
@driskell  I forgot to repport, but I arrived at the same conclusion as you on your 2 first paragraph,  I'm not knowledgeable enough for the 3rd one, I don't know how much  symfony process abstract that is actually needed here

**Comment by mnapoli** [comment]
Thanks a lot @driskell, that is extremely helpful! I will try to work on that topic asap!

**Comment by mnapoli** [comment]
Great news, thanks to @driskell I was able to work on a fix. I was also able to reproduce the bug and test it went away (both locally and in Lambda) thanks to your snippets @allan-simon and @alexw23.

Fix here: https://github.com/brefphp/bref/pull/1852

Is anyone able to test that branch to confirm this improves things? 🙏

**Comment by alexw23** [comment]
This is great @mnapoli. Haven't had a chance to test yet but from my own debugging it looks like this will work.
