### ISSUE TITLE
Bref v2 dev images cannot support parallel requests

### ISSUE THREAD

**Issue by shadowhand** [brefphp/bref#1471]
**Description:**

The new dev images, merged in #1356, bring local execution to near perfect parity with AWS. However, this parity comes at an extreme cost: **parallel requests are no longer supported**.

This is a serious regression that is not documented anywhere and, at least for our dev team, makes the new images completely unusable.

**How to reproduce:**

Open any local URL that is handled by `bref/php-8x-fpm-dev` and refresh it quickly. Any request that happens before the other is completely finished (and it seems there is a ~300ms delay after the request appears finished) will result in:

```
400: UnknownError
    at throwDefaultError (/local-api-gateway/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restJson1InvokeCommandError (/local-api-gateway/node_modules/@aws-sdk/client-lambda/dist-cjs/protocols/Aws_restJson1.js:3795:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /local-api-gateway/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /local-api-gateway/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /local-api-gateway/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /local-api-gateway/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
```

And when you look at the logs of the container you will see:

```
[ERROR] (rapid) Failed to reserve: AlreadyReserved
```

Searching for this error message may you lead you to [this SO answer](https://stackoverflow.com/a/72288720/49146) which states:

"Unfortunately, you won't be able to execute multiple requests in parallel locally."

So while the new container image may be fine for one-off web requests, it absolutely is not usable for a development environment that includes an SPA that relies on being able to make multiple parallel HTTP requests.

**Comment by dhrrgn** [comment]
I was curious how LocalStack does it since it's next version will also use the official lambda images for parity. So, I did some digging:

They handle concurrent requests by starting a background thread that listens for new invocations to be queued.

When a new invocation is queued it first checks if there are any available containers, if so, run it there. If not, it wall start another container and then use it. The containers automatically stop after 10 minutes.

**Comment by mnapoli** [comment]
Thank you for the report.

I understand how this can be frustrating and disappointing when you expect a smooth experience upgrading from v2.

I'll be honest, I think some of the wording used here and on slack could use a bit less urgency ("serious regression", "not documented anywhere", "completely unusable", "absolutely is not usable", "it seems like a truly terrible choice", "this is so broken"), at least on my end it was quite anxiety-inducing, until I was able to dig more into this while away on holidays (was available for urgent bugfixes). I'm sharing this because I don't think any harm was meant, but I felt like Ineeded to give my perspective too.

This is a dev tool, production is not impacted, the image does work but with (indeed very) degraded DX. This is not the intended experience, it wasn't an intentional regression (which is why it wasn't documented). Let's work on this and fix this, I'm confident we'll end up with a solution.

I'll work on this first thing Monday morning.

**Comment by shadowhand** [comment]
That's for letting me know. Let's take the urgency within the context of: I am aware this is a dev tool, therefore much less critical than a production issue.

I do think it is a serious regression in _developer_ usability for a _recommended_ tool and it was quite frustrating for myself and our dev team.

**Comment by mnapoli** [comment]
@dhrrgn thanks for the context, that was useful.

So far it would be hard to start multiple containers, as we're relying on `docker-compose.yml` to start them for us. I looked into starting multiple instances of the same container (via replicas), but this is a bit more advanced for users.

As a first step, I have https://github.com/brefphp/local-api-gateway/pull/1 which queues parallel requests.

I think the first benefit of this is that users should not be facing errors anymore. The downside is that in case of a lot of parallel requests, all requests could be a bit slower to process. I'm thinking for example of an admin dashboard where a lot of AJAX requests are made from a single page.

I'd be interested in your feedback here: I'm thinking of shipping this first solution right now. We could explore more advanced solution down the road.

**Comment by shadowhand** [comment]
I think this is a step in the right direction, and it would at least allow multiple requests to be processed, even if there is high latency.

**Comment by mnapoli** [comment]
@shadowhand you can now do `docker compose pull` and test the new images.

Let me know if you spot any problems.

**Comment by shadowhand** [comment]
@mnapoli were these changes applied to `bref/php-81-fpm-dev`? I don't see any new version listed on hub.docker.com.

**Comment by shadowhand** [comment]
@mnapoli well, now we see a different error:

```
php  | /local-api-gateway/dist/apiGateway.js:44
php  |             throw new Error('Unexpected query parameter value');
php  |                   ^
php  | 
php  | Error: Unexpected query parameter value
php  |     at /local-api-gateway/dist/apiGateway.js:44:19
php  |     at /local-api-gateway/dist/apiGateway.js:83:23
php  |     at Array.reduce (<anonymous>)
php  |     at objectMap (/local-api-gateway/dist/apiGateway.js:82:32)
php  |     at httpRequestToEvent (/local-api-gateway/dist/apiGateway.js:39:33)
php  |     at /local-api-gateway/dist/index.js:100:61
php  |     at step (/local-api-gateway/dist/index.js:33:23)
php  |     at Object.next (/local-api-gateway/dist/index.js:14:53)
php  |     at /local-api-gateway/dist/index.js:8:71
php  |     at new Promise (<anonymous>)
```

The first few requests work, and then we get this, and then the server appears to die and no longer handles any requests.

**Comment by mnapoli** [comment]
FYI an update here, I worked on this today, didn't push a fix yet.

**Comment by shadowhand** [comment]
@mnapoli appreciate it.

**Comment by mnapoli** [comment]
PR: https://github.com/brefphp/local-api-gateway/pull/2

Will work through releases.

**Comment by shadowhand** [comment]
@mnapoli I have confirmed that the newly released image solves both of the issues mentioned here. For obvious reasons, it is still much slower to use the new images, so our dev team will probably continue to use 1.7.x locally, until parallel requests actually execute in parallel.

Appreciate your efforts to get this resolved!
