### ISSUE TITLE
Slim framework documentation for v0.3

### ISSUE THREAD

**Issue by gregmsanderson** [brefphp/bref#151]
I recall from previous Bref versions, there being examples of using Slim framework (http://www.slimframework.com/). But in 0.3's docs, only Symfony and Laravel are listed. Does that mean Slim framework is no longer supported? Or is it so simple, no specific files are needed to make it work as a HTTP application?

**Comment by mnapoli** [comment]
> Or is it so simple, no specific files are needed to make it work as a HTTP application?

This is it basically.

Bref 0.3 provides a runtime that runs PHP-FPM. So anything that runs with PHP-FPM (aka anything in PHP) works on Lambda.

**However** there are framework-specific guides because Lambda still has a few specificities. For example:

- the filesystem is readonly, meaning some framework caches (like Laravel/Symfony) must be generated before deploying when applicable
- because of that the logs must also not be written to disk (so we provide Symfony & Laravel config to help people get started)
- same with sessions: must use a database or redis or something like this

It would make sense to write a Slim guide as well since it's a pretty popular framework. Let's keep this issue open to track that.

**Comment by gregmsanderson** [comment]
I see, that makes sense. Thank you.

**Comment by aknosis** [comment]
I recently deployed a Slim application using bref and no framework changes were required to make it work as expected.

(It was a very simple and lightweight application)

**Comment by gregmsanderson** [comment]
@aknosis Interesting. I've since been playing with Laravel so didn't pursue this.

Perhaps then a single line to say Slim is supported could be added to the docs, and this issue closed.

**Comment by mnapoli** [comment]
It is pretty simple indeed, and I've been using Slim as my default framework on Lambda since it fits really well the use case.

However I do use the same thing every time:

- setup CORS as described in #252
- setup Monolog to log into stderr as described below:

```php
$logger = new Logger('app');
/** @noinspection PhpUnhandledExceptionInspection */
$logger->pushHandler(new StreamHandler('php://stderr', Logger::NOTICE));
$container = $app->getContainer();
$container['phpErrorHandler'] = $container['errorHandler'] = function () use ($logger) {
    return function ($request, Response $response, Throwable $error) use ($logger) {
        $logger->error($error->getMessage(), [
            'exception' => $error,
        ]);
        return $response->withStatus(500)
            ->withHeader('Content-Type', 'text/html')
            ->write('Something went wrong!');
    };
};
```

That part looks overkill though… I would want to make it simpler, maybe I missed something about Slim to make it log by default in Monolog (or any other stderr logger actually).

**Comment by aknosis** [comment]
My bref app runs http and has a lambda function triggered via schedule so I wanted html error output in the browser, but json for api requests and cli runs.

To do this, I used an anonymous class to extend the default Slim handlers and reuse the code that provides different output based on the Accept request header. 

```php

$formatter = new \Monolog\Formatter\LineFormatter(null, null, false, true);
$logger = new \Monolog\Logger('app');
$handler = new \Monolog\Handler\StreamHandler('php://stdout', \Monolog\Logger::DEBUG);
$handler->setFormatter($formatter);
$logger->pushHandler($handler);

$container = $app->getContainer();
$container['phpErrorHandler'] = function () use ($container, $logger) {
        return new class($container->settings['displayErrorDetails'], $logger) extends \Slim\Handlers\PhpError
        {

            /** @var \Monolog\Logger */
            private $logger;

            public function __construct($displayErrorDetails = false, \Monolog\Logger $logger = null)
            {
                parent::__construct($displayErrorDetails);
                $this->logger = $logger;
            }

            public function __invoke(
                \Psr\Http\Message\ServerRequestInterface $request,
                \Psr\Http\Message\ResponseInterface $response,
                \Throwable $error
            ) {
                $this->logger->error($error->getMessage());
                return parent::__invoke($request, $response, $error);
            }
        };
    };

    $container['errorHandler'] = function () use ($container, $logger) {
        return new class($container->settings['displayErrorDetails'], $logger) extends\Slim\Handlers\Error
        {
            //basically same code as above just extends a different class
        };
    };
```

**Comment by maverick108** [comment]
Hi,
I am having an issue getting the request context to SLIM.
It's not able to get the routes properly,  it always returns a page not found error. Do I need to write a custom HTTP handler?, How do I pass same to Bref
