### ISSUE TITLE
php-rdkafka extension

### ISSUE THREAD

**Issue by marcospassos** [brefphp/bref#310]
It looks like lambdas are perfect for message producers. Would you consider adding support for Kafka by including the extension https://github.com/arnaud-lb/php-rdkafka?

**Comment by mnapoli** [comment]
After a first look extensions like this would be good candidates to be distributed via a separate layer. The main reason for that is that this extension isn't a standard/common extension for PHP applications and (that's to be confirmed) since it's a separate `.so` I expect this would make the layer heavier.

If you manage to compile this extension feel free to share some information here for others.

**Comment by mnapoli** [comment]
We now have a repository where you can send contributions: https://github.com/brefphp/extra-php-extensions
