### ISSUE TITLE
Submit APN and try to become AWS Partner?

### ISSUE THREAD

**Issue by deleugpn** [brefphp/bref#327]
Have you tried to submit a request through the APN Portal to become an official Lambda Partner? Bref is undeniably  better than stackery.io and it might bring some good visibility to the project.

https://aws.amazon.com/lambda/partners/

https://partnercentral.awspartner.com/SiteLogin?startURL=/apex/partnerAccount

**Comment by mnapoli** [comment]
That's a very good idea, I will try that!

**Comment by atrope** [comment]
I Second that Bref Layer > Stackery Layer.

@mnapoli Let me know how they respond, because i might have someone i can contact to help us.

**Comment by nealio82** [comment]
> undeniably better than stackery.io

I think that's got to go on the website as a testimonial! 😆

**Comment by Rodenastyle** [comment]
Such a good idea!

**Comment by mnapoli** [comment]
I have finally registered on the AWS APN with the goal of having Bref displayed on https://aws.amazon.com/lambda/partners/

On top of registering to the APN (which doesn't seem to do anything beyond creating an account, which I did under the "Null" company), I have submitted Bref as a "_solution_". I hope this is the correct procedure, we'll see what happens.

**If you have a contact at AWS maybe it could help if you let them know about it?**

All the forms I have filled left little place for details. From AWS point of view, they will not have many details: people reviewing the submission will have no idea if the project is actually used or not by current AWS customers.

I'll keep you updated here.

**Comment by mnapoli** [comment]
Someone from AWS got in touch with me, we'll set up a call to discuss Bref and what is best to add it to the APN.

**Comment by mnapoli** [comment]
I finally managed to get a response from someone and planned a meeting, but got stood up. Trying to set up another meeting…

Unfortunately this takes a lot of time :/

**Comment by mnapoli** [comment]
OK I managed to get in touch today! There are some good and not-so-good news:

- I need to submit as a technology partner to land right next to Stackery here: https://aws.amazon.com/lambda/partners/
- I need to get to the "Select" level:
  - I need to become [certified](https://aws.amazon.com/fr/certification/) (Developer, SysOps or Architect associate), which costs about $150
  - Bref needs to have 1 public reference: easy
  - I need to provide a list of 3 companies using Bref paying a total of more than $1500/month to AWS: doable if some of you can help ^^
  - I need to pay $2500 per year: yuck

The $2500/y paid to AWS will get me $3000 of credit into my AWS account (which wouldn't be that useful to me since I spend $20 per month on AWS).

I'm going to think over this for a few days.

**Comment by deleugpn** [comment]
Yeah, most of these points are easy to manage, even the certification. But the yearly cost to be a partner is way too expensive. I guess it would only make sense if you could get a company behind to pay it for you and get the credit. If a company is already paying that to AWS anyway, it could sort of make sense, but it brings some complex overhead.

Might not be as good as I thought.

**Comment by depach** [comment]
please keep us updated, we are not using bref yet but I am looking at it and our spend is quite big on aws

do you have to be certified yourself? or anyone part of the project

**Comment by depach** [comment]
just to clarify my comment was in relation to having 3 companies using bref :)

**Comment by mnapoli** [comment]
@depach :+1: I would have to be certified or someone from my company (which means me or me ^^). That point isn't that much of a blocker though.

FWIW I haven't made any specific decision yet, but I'm thinking that if I can put those $3000 credits to use (e.g. sell a service or host apps), then those $2500 are not lost and therefore would be an investment I could make. So by the way: if anyone wants their PHP app online and do not want to deal with deployment and hosting, get in touch with me 😉

**Comment by italo1983** [comment]
>     * I need to provide a list of 3 companies using Bref paying a total of more than $1500/month to AWS: doable if some of you can help ^^

$1500/month in total or 1500x3? I've some customer spending more than $500/month on AWS and using bref.sh

**Comment by atrope** [comment]
> I need to provide a list of 3 companies using Bref paying a total of more than $1500/month to AWS: doable if some of you can help ^^


@mnapoli we spend much more than that and i'd gladly send an email to anyone (suamusica.com.br)

**Comment by mnapoli** [comment]
@italo1983 & @atrope thanks! 

OK here is an update:

![Capture d’écran 2019-09-19 à 15 03 49](https://user-images.githubusercontent.com/720328/65246445-ea54ac00-daee-11e9-95e5-7f751a39b1af.png)

## About Null

Null is the company I created in January, and the company is backing Bref financially. I am explaining that because everything related to the AWS Partner program needs to go through a company, this is why most of what you will read below is about Null.

## 5 Customer Satisfaction Responses

This seems easy to attain: anyone (using Bref of course) can write a "customer review". That customer review is about Null (see the section above) but Bref being provided by Null, I guess you can write about whether you are happy or not about Bref.

Here is the form: https://partnercentral.awspartner.com/CreateReview?pid=0010h00001c9ln7AAA

## 3 Launched Opportunities

Regarding the "3 launched opportunities with $1500/month":

> Maintain a total number of newly “Launched” opportunities over a rolling 12-month period with a total combined estimated monthly recurring revenue (MRR) minimum. All opportunities are to be tracked and managed via the Opportunity Management tool.

It seems it's $1500 in total.

Here is the screen to add an opportunity:

![screencapture-partnercentral-awspartner-CreateOpportunity-2019-09-19-15_06_39](https://user-images.githubusercontent.com/720328/65246565-22f48580-daef-11e9-89f0-96fbf533169d.png)

It seems that opportunities are supposed to be added in the dashboard *before* the app is launched because the Target Close Date cannot be in the past. But we could try to add an existing application and see what AWS says.

To be transparent on this, here is what submitting that form would mean (from what I understand): Null provided you with a tool (Bref) to help you achieve your project on AWS. The tool is open source, and there was no contract between us, so I'm not sure how that will affect the submission. But there's only one way to know ;)

If you want to give it a try, @italo1983, @atrope or anyone up for it please send me an email: matthieu@mnapoli.fr

## 1 Publicly Referenceable Customer

> Need to designate previously launched opportunities as publicly referenceable via the Opportunity Management tool in APN Partner Central. Details relating to publicly referenceable opportunities may be displayed in AWS Marketing material, the Partner Solutions Finder (PSF) and AWS Webpages.

Let's first try to add a few opportunities…

**Comment by atrope** [comment]
I can fill that form. Send to me to alan@suamusica.com.br :)

**Comment by mnapoli** [comment]
APN submissions are rejected because the projects are already in production… I don't know what to do, this is frustrating.

**Comment by deleugpn** [comment]
That's a horrible argument to make against the case and a GREAT argument to make in favor: "Look, you're already making money off of people using my Layer. If I drop my layer, it's gonna affect **your** customers". The opposite makes no sense. "Oh well, we're already earning that money anyway, go away".

**Comment by mnapoli** [comment]
I have emailed my APN contact to ask for more details.

In the meantime there is also this form that Bref users can fill out: https://partnercentral.awspartner.com/CreateReview?pid=0010h00001c9ln7AAA This is a way to add a "Customer satisfaction response" (at least 5 are required).

**Comment by mnapoli** [comment]
I finally have one opportunity registered. Still looking for more, if you are setting up Bref in a project moving to production you can help :) Send me an email at matthieu@mnapoli.fr

**Comment by mnapoli** [comment]
Closing this since it's been going nowhere.

In the meantime, we managed to get the attention of AWS through other means 💪
