### ISSUE TITLE
 request timed out using curl or get_file_content

### ISSUE THREAD

**Issue by wladimiravila** [brefphp/bref#374]
Hi everyone, I was trying to get information from another host, without success, no matter if I try by get_file_contents or even curl the answer in both cases are  time out  #55 

In both cases the response could be big from the another host, for curl case I'm setting up Content-Length #162    

Fatal error: Uncaught Bref\Runtime\FastCgi\FastCgiCommunicationFailed: Error communicating with PHP-FPM to read the HTTP response. A root cause of this can be that the Lambda (or PHP) timed out, for example when trying to connect to a remote API or database, if this happens continuously check for those! Original exception message: hollodotme\FastCGI\Exceptions\TimedoutException Read timed out in /var/task/vendor/bref/bref/src/Runtime/PhpFpm.php:126

For case get_file_contents the error was  Operation now in progress

my conf:  bref/bref  0.5.0, symfony 4.3

if someone knows how to fix this trouble, I really appreciate it
Regards!

**Comment by victormacko** [comment]
Is the Lambda in a VPC? ... if so, have you got NAT gateway setup (otherwise Lambda can't connect to anything outside of the VPC (nor other AWS resources)

**Comment by mnapoli** [comment]
Hi, it is indeed a timeout in your lambda (your code is taking too much time).

There isn't much we can do to help, except try to point you to probable causes. As @victormacko mentioned check if your database connection is correct (e.g. if using a VPC), and check where the timeout is coming from (what is hanging).

Setting short timeouts in your code (e.g. for database connections or in HTTP clients) can help identify where the source of the problem is.
