### ISSUE TITLE
serverless components

### ISSUE THREAD

**Issue by patie** [brefphp/bref#391]
hi,

what about compatibility with serverless components? https://serverless.com/blog/serverless-components-beta

**Comment by patie** [comment]
maybe this can help https://github.com/serverless/components/issues/465

**Comment by mnapoli** [comment]
Hi, yes I have started looking into that already.

I will be closing this because there isn't really a task, feature or use case behind this issue (I want to try to keep the issue tracker up to date). Let's open pull requests or issues with use cases that we have identified to cover using components. Until then, let's explore ;)

**Comment by patie** [comment]
@mnapoli any news sir?

**Comment by mnapoli** [comment]
Nothing at the moment! I think components are very promising, but the fact that they break completely from the existing behavior and configuration format is a problem.

I think it's worth experimenting with it for now.
