### ISSUE TITLE
"robots.txt" and "assets" are not displayed in Laravel, index.php is displayed

### ISSUE THREAD

**Issue by YuK1Game** [brefphp/bref#437]
Set serverless.yml according to the formula.

```serverless.yml
service: my-project

provider:
    name: aws
    region: ap-northeast-1
    runtime: provided
    environment:
        APP_STORAGE: '/tmp'

plugins:
    - ./vendor/bref/bref

functions:
  website:
      handler: public/index.php
      timeout: 30
      layers:
        - ${bref:layer.php-73-fpm}
      events:
        - http: 'ANY /'
        - http: 'ANY /{proxy+}'
  artisan:
    handler: artisan
    timeout: 120
    layers:
        - ${bref:layer.php-73}
        - ${bref:layer.console}
```

index.php is displayed normally

When accessing /robots.txt, index.php is displayed

Accessing `/routing/pages` shows routed pages.

What other settings are required?

Thanks

**Comment by victormacko** [comment]
Lamda doesn't load static files (non-php files) in the same way standard hosting does ... you'll need to upload static assets (eg. images/css/etc) to something like S3 (this serverless plugin might help; https://serverless.com/blog/deploy-serverless-frontend-with-serverless-finch-plugin/) ... and within laravel somehow have the assets loaded from there rather than the same spot your app is located (i'm a Symfony person not laravel so not sure how this is done!).

I'm guessing you'll need to create an endpoint for the robots.txt file within laravel (i'm assuming a redirect to s3 for search-engines to follow wouldn't work, but i'll happily be correct otherwise).

**Comment by mnapoli** [comment]
This is indeed documented in https://bref.sh/docs/websites.html, I'll be closing this.

Feel free to ask if you have questions that we haven't answered.
