### ISSUE TITLE
Exceeds max allowed size

### ISSUE THREAD

**Issue by wsheldon** [brefphp/bref#450]
Hi there,

I've started getting an 'exceeds max allowed size' error today.  Could this be related to the new runtimes?  If not, I'll dig further into it.

Thanks again for the great work!  Here's the error

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service app.zip file to S3 (18.86 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A494519901673%3Astack%2Fapp-dev%2F133d7f40-c5e9-11e9-b91a-121b5b00f9e8
 
  Serverless Error ---------------------------------------
 
  An error occurred: ApiLambdaFunction - Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 267227776 bytes. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 6db3db60-0548-421a-8c23-7624f8e8bb67).

**Comment by mnapoli** [comment]
Hi, if by "new runtimes" you mean the one I generated for the GD extension then probably not: I published it just 1 hour ago, and it's not available on Bref 0.5.5 (the current stable release). You would have to install the beta version to test it.

Given you are just above the limit it's maybe just a few things that tipped over the limit?

Make sure that you exclude all the assets, tests, dev caches or logs, etc. when deploying. If you see something wrong with a Bref release/new runtime let us know, in the meantime I will close this because (unless it's more complex than it appears) we can't do much to help you unfortunately.

**Comment by mnapoli** [comment]
:+1: and just so you know there are 2 limits:

- the zipped size (50Mb IIRC)
- the unzipped size (250Mb)

Both limits also include the size of layers, which means the Bref PHP runtime counts in that. It's like 25Mb zipped and 70Mb unzipped.

**Comment by mnapoli** [comment]
(and we are always looking into ways to make it slimmer)
