### ISSUE TITLE
Using SAR

### ISSUE THREAD

**Issue by postme** [brefphp/bref#458]
Have you considered using SAR rather than direct Lambda layers? 
https://serverless.pub/sar-layers/
With SAR your layers are globally available, semversioned and the layer is deployed to the client account making it independent

**Comment by mnapoli** [comment]
> Have you considered using SAR rather than direct Lambda layers?

I have, but I didn't try anything because what we have for now works. The solution mentioned in the article has a few interesting advantages, but it also seems to require a little bit of complex YAML (by complex I mean that a PHP developer not familiar with Lambda will not really see the point or understand).

However, let's keep this issue open. If you or anyone has an idea to improve Bref by using this, feel free to suggest it here.

**Comment by mnapoli** [comment]
Not planned at the moment, I'll close this.

Thanks for the suggestion though!
