### ISSUE TITLE
bref/php-73-fpm-dev fails to start

### ISSUE THREAD

**Issue by ttsuru** [brefphp/bref#461]
Docker image bref/php-73-fpm-dev (DIGEST: 92f5601d99eb) fails to start

```
/opt/bin/php-fpm: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
exited with code 127
```

**Comment by mnapoli** [comment]
Thank you for the report, that seems to reflect what I experienced here: https://github.com/brefphp/bref/pull/396#issuecomment-530282487

I dismissed it (because I have a lot of dev docker images on my machine) but it seems it's actually a real problem.

I wonder why that lib is missing in Docker, but not on AWS Lambda 🤔

**Comment by ttsuru** [comment]
Sorry for duplicate 😢

**Comment by ttsuru** [comment]
I think `bref/php-73-intermediary` referring to the old cache image and isn't the problem?
How do you release a Docker container?

**Comment by mnapoli** [comment]
Oh sorry I didn't mean it's a duplicate, the link I added was in a pull request. Let's keep that issue open.

I confirm that the problem exists only with `php73-fpm-dev`, other images work fine:

```
❯ docker run --rm -it --entrypoint php bref/php-73 -v
PHP 7.3.7 (cli) (built: Sep 19 2019 12:56:26) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7, Copyright (c) 1999-2018, by Zend Technologies

❯ docker run --rm -it --entrypoint php bref/php-73-fpm -v
PHP 7.3.7 (cli) (built: Sep 19 2019 12:56:26) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7, Copyright (c) 1999-2018, by Zend Technologies

❯ docker run --rm -it --entrypoint php bref/php-73-fpm-dev -v
php: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

It may be because fpm-dev is the only image not to `FROM` the lambci image, like [other images](https://github.com/brefphp/bref/blob/02cfbe770ab5f630e377f42d267f47fdecb3008f/runtime/layers/fpm/Dockerfile#L9). Instead it's `FROM` the AmazonLinux image 🤔 

> How do you release a Docker container?

This is the `make docker-images` command in the root Makefile.

**Comment by mnapoli** [comment]
Fixed, thanks for reporting!

**Comment by ttsuru** [comment]
Thanks for fixed👍
