### ISSUE TITLE
Codeigniter in AWS Lambda

### ISSUE THREAD

**Issue by anandvns** [brefphp/bref#489]
Getting Error Message: Undefined index: SCRIPT_NAME

please check
https://sspzzrogbl.execute-api.ap-south-1.amazonaws.com/dev/

**Comment by mnapoli** [comment]
Closing in favor of #441

**Comment by jaulz** [comment]
@mnapoli since I can't see it in the other issue, do you know why `SCRIPT_NAME` is not set at all in general?

**Comment by mnapoli** [comment]
@jaulz it seems like it's indeed missing (and should be here).

I think the main step needed to add this is to investigate exactly what its value should be so that we replicate the correct behavior.

Note that if you want to get unstuck quickly, you can manually define that variable in your index.php befor CI runs.

**Comment by jaulz** [comment]
Yep, thanks for the hint, that's what I'm doing now in my `index.php`:
```php
if (isRunningInLambda()) {
  $_SERVER['SCRIPT_NAME'] = '/index.php';
}
````

Someone seems to have worked on it before but I'm not sure if that makes sense?
https://github.com/brefphp/bref/pull/479/files#diff-13c17eee69d58269e50e1873088b1ab8c0ebb55bdfbac0a050e23f388de99e89R189
