### ISSUE TITLE
BREF_AUTOLOAD_PATH should only contain the directory path

### ISSUE THREAD

**Issue by thejoshsmith** [brefphp/bref#559]
I've just started playing around with Bref in the last few days (which works great by the way!), and I was hoping to create a layer for my composer dependencies—so I was stoked when I saw #556 had been merged in.

After setting up a layer with my vendor folder in it and configuring CraftCMS to use the new path , I'm wondering whether the `BREF_AUTOLOAD_PATH` env variable should only contain the path to the autoload directory and not contain `autoload.php`.

My reasoning for this is that in CraftCMS (and Symfony + other frameworks) the autoload path has `autoload.php` appended to it (similar to Bref and $appRoot), so I've had to do a str_replace() to make it work. I could've just overwritten the bootstrap file, but Yii2 aliases the path to `@vendor` and I think this approach keeps it more flexible.

**CraftCMS index.php**
![Screen Shot 2020-02-16 at 10 41 04 AM](https://user-images.githubusercontent.com/5515179/74595647-09a93280-50a9-11ea-9d77-43dbb954f283.png)

**Symfony Bootstrap**
![Screen Shot 2020-02-16 at 10 54 30 AM](https://user-images.githubusercontent.com/5515179/74595786-bfc14c00-50aa-11ea-8e90-df2193919833.png)

I realise this is a breaking change but hopefully not too many people have started to use the new env variable.

**Comment by jasonmccallister** [comment]
@thejoshsmith that is a pretty strong point, the name does not indicate file, but instead path. For Craft, I have just been hard coding `CRAFT_VENDOR_PATH` to look like this:

```php
define('CRAFT_VENDOR_PATH', '/opt/vendor');
```

In my use case, I was not really worried about the path for Craft - since we can override the paths per install, but more about the ancillary functions. However, I think your change makes sense and curious to hear what @mnapoli has to say about it.

**Comment by mnapoli** [comment]
I did not realize about the Symfony "vendor dir" option. What you suggest makes sense.

However, I figured it was a good thing to ask for an autoloading file instead of Composer's vendor path because that means that applications not using Composer can work as well. This is a good thing for legacy applications as well as future-proof (in case somehow there's an alternative to Composer).

It sounds to me more flexible at a very little cost. WDYT?

**Comment by jasonmccallister** [comment]
So would the idea be to keep the `BREF_AUTOLOAD_PATH` and add `BREF_AUTOLOAD_FILE` but default the file to `autoload.php`? 

If that is the case I can make that change and submit a PR. I think that would satisfy both requirements of supporting composer and other dependency managers.

**Comment by mnapoli** [comment]
I would rather not have too many options. Is it really necessary to support customizing the directory only?

**Comment by mnapoli** [comment]
Hi both, I will close this for now, I don't think it makes sense to change this for the moment.
