### ISSUE TITLE
Explain "version" in runtimes table

### ISSUE THREAD

**Issue by roenschg** [brefphp/bref#588]
The website https://runtimes.bref.sh/ will show the available runtimes in the different regions.

The last column contains a "version" but it is unclear what that version refers to and it is unclear with which bref version the runtime is compatible to.

Would it be possible to add a column which describes the used/compatible bref version for that runtime.

**Comment by mnapoli** [comment]
Hi,

The Bref version can be selected at the top of the page:

![Capture d’écran 2020-03-13 à 21 47 14](https://user-images.githubusercontent.com/720328/76658372-46ffc380-6574-11ea-8649-4ad96b84b0e4.png)

The version is the layer version. Hopefully that clears things out. Adding a new column wouldn't make sense I think because the Bref version is selected for the whole page.

Maybe the column "Latest version" could be renamed to "Layer version"? Would that help?

FYI if you want to send a pull request, here is the repository: https://github.com/brefphp/runtimes.bref.sh
