### ISSUE TITLE
Inconsistency between lambda layers on different regions?

### ISSUE THREAD

**Issue by deleugpn** [brefphp/bref#725]
I was getting an error today when trying to deploy layer `arn:aws:lambda:${AWS::Region}:209497400698:layer:php-73:26` across EU, US & Australia and Australia was failing because there's no layer `26`.
I was wondering what could be the reason for a specific layer not being available on a specific region. Is the layer 26 missing from Australia or the version 25 is the same as 26 in Europe?

**Comment by mnapoli** [comment]
You can have a look at https://runtimes.bref.sh/ and play with the regions, the numbers are not synchronized. Some regions were added later, and we have no control over the version numbers (they are autoincremented).

Once, I tried to deploy over an unreliable network and managed to deploy most regions, but the process stopped. I had to retry, but that's why some regions have more releases than others. It sucks, but that's also why I pushed a lot for using the serverless variables instead of the numbers themselves, because they are prone to errors.

**Comment by deleugpn** [comment]
Got it, thanks! For now I'm falling back to `25` and if it ever becomes a huge issue, I'll have to create an SSM Parameter in each region representing their own layer number

**Comment by mnapoli** [comment]
If it can help, we could add a command like this in Bref: https://github.com/brefphp/bref/pull/664#issuecomment-653584654
