### ISSUE TITLE
Decrypt SSM at runtime

### ISSUE THREAD

**Issue by allan-simon** [brefphp/bref#901]
Currently the procedure explained by the documentation has a major drawback in term of security, as anyone with access to the AWS console can see the decrypted variables into  the lambda configuration.  Instead the best practices is to decrypt at runtime (once during the init phase of the lambda)

Not being a symfony, and even less a bref expert, I'm wondering if it's something that can be directly done transparently by bref so that the other of the application do not need to know the environment variables where encrypted 

(currently in my EC2 deployement for example, the .env.local file  is encrypted with KMS and uncrypted during provisionning)

**Comment by mnapoli** [comment]
Bref documents the basic way to get started. If a company has more advanced requirements regarding configuration variables, then decrypting secrets at runtime makes sense, but it's up to them.

I'm more than happy to merge a pull request that adds a paragraph [in this section](https://bref.sh/docs/environment/variables.html#secrets) mentioning that this is a possibility. Even a link to an example, a blog post, or a package.

But I don't think this should be baked in Bref. You would get the same problem with any other hosting solution, you'd have to do something to decrypt the secrets. What you mentioned with EC2 is not solved by PHP, so I think it shouldn't be solved by Bref.

Maybe a PHP package? Or a Symfony bundle? Maybe a serverless plugin? Maybe something else?

**Comment by matthewsuan** [comment]
@mnapoli i how do we hook up a function or code during the init phase using Bref? I looked into `bootstrap` file but cant find anything there that we can hook up to.

**Comment by allan-simon** [comment]
I understand your point and they make sense , however I would have one counter argument:

  * bref is made specifically to my understanding to be a AWS Lambda <-> PHP wrapper to make AWS Lambda an implementation detail, as such it does not seem that strange to me , that bref also abstract the secret management part,
 

however I have to admit I don't know yet how I would implement it on bref side in way that is not too much opiniated

@matthewsuan right now what I'm  doing is putting my code loading the environment variable in the index.php , just before booting the kernel (where the DotEnv files are read)

**Comment by mnapoli** [comment]
> how do we hook up a function or code during the init phase using Bref? I looked into bootstrap file but cant find anything there that we can hook up to.

I get this question a lot and always answer the same thing :) -> how would you solve that in any other PHP project?

Here is what I would suggest: in `index.php` or your framework bootstrap fetch the secrets and decrypt them. Then cache them (on disk, in APCu, or anywhere you want). It's simple and decoupled from Lambda.

> as such it does not seem that strange to me , that bref also abstract the secret management part,

Yes I see your point. Feel free to suggest a specific solution. I'll be honest, it's hard to be 100% sure when we are talking about abstract features. Maybe you have something in mind that I haven't imagined that would indeed be great.

Here is one thing that I think could be awesome:

```
composer require bref/secrets-decrypter
```

Then:

```php
<?php
// index.php

$decryptedValues = Bref\SecretsDecrypter\SecretsDecrypter::fromSecretsManager(/* secret ID ? */);

// inject those values in your framework
```

Also some features that could be added:

- caching with a PSR-6/PSR-16 driver, or even auto-caching in `/tmp` or APCu (after all, we know we are on Lambda)
- a method to auto-populate environment variables? (that way it's easy to integrate with any framework)

Anyway, that being a separate project from Bref itself makes sense I think, because you intentionally activate it. It's not magic.

**Comment by deleugpn** [comment]
@matthewsuan if you use the Bref as any other Lambda Runtime provider (https://bref.sh/docs/runtimes/function.html), then anything executed outside of the callback is considered the Execution Context (https://docs.aws.amazon.com/lambda/latest/dg/runtimes-context.html) and will only impact your cold start once.

The unique situation here is that Bref is already going overboard and providing PHP-FPM compatibility with AWS Lambda, which means we have a powerful and easy-to-use Web Server, but we lose AWS Execution Context concept i.e. anything executed by Bref during the loading of your next invocation is isolated from your PHP-FPM execution.

It's easy enough to offer a library that would decrypt secrets during cold-start, but PHP-FPM wouldn't make use of that. We would then need an opinionated way to set environment variables from Bref Invocation in a way that it reaches PHP-FPM so that you wouldn't need decryption once every invocation.

**Comment by matthewsuan** [comment]
@mnapoli thanks for the quick response.

what I think and please correct me if my assumptions are wrong is maybe we can include a file in `bootstrap` for example and call it if it exists in environment variable.

```
...

/**
 * Require an init handler file, if provided, just 
 * before the start of the invocation phase.
 */
if (getenv('BREF_INIT_HANDLER')) {
    /** @noinspection PhpIncludeInspection */
    require getenv('BREF_INIT_HANDLER');
}

$phpFpm = new FpmHandler($handlerFile);
try {
    $phpFpm->start();
}
...
```

Is something like this possible? I will open a PR if you agree. 

Then this is where @allan-simon can put the code for ssm related fetches.

**Comment by deleugpn** [comment]
@matthewsuan that will not work because FPM is a separate process and isolated from that code execution.

**Comment by matthewsuan** [comment]
@deleugpn runtime and fpm may be isolated but can you enlighten me why environment variables set during coldstarts are inaccessible  by the fpm process? 

thanks for the quick response, btw.

**Comment by deleugpn** [comment]
@matthewsuan if you mean set an environment variable on the hosting OS that will then "leak" to the FPM process, I guess that never occurred to me. It might be an option, but I'm not sure how good of an option it is.

**Comment by matthewsuan** [comment]
@deleugpn we can do all kinds of initialization tasks if we can call a user-defined file during init. setting env vars is one of them. In laravel apps, we can create .env file based on the results from ssm or secrets manager fetch. possibilities are endless. Giving the users an option to define init file, I think, is a good option. 

Requiring the file during init process, as you've said, is isolated and would not affect the performance of the fpm process (given it can be completed < 10 secs). No application-specific code is involved. It's one file that the user can optionally define to do init tasks, nothing more.

What do you think @mnapoli?

**Comment by mnapoli** [comment]
@matthewsuan regardless on whether this is possible, I do not want to do that.

Because there is no reason to do that. We don't need that, so if we can avoid doing exotic stuff we should. Let's stick to standard PHP unless we have no other choice.

See my previous comment for "how to do that with vanilla PHP".

**Comment by matthewsuan** [comment]
There is clearly a reason to do it -- to allow users to run code during init phase which is one of the most important phases in a lambda lifecycle. Without that, imo, bref becomes a handicapped lambda runtime. I think the reason is there and a need is there.

As for exotic, I think lambda is exotic enough that it requires you to think outside the box and bref is a great example of that. Requiring a PHP file is still a standard php way of doing things, imo. That's exactly how you do preload in PHP - by requiring a file.

Although I disagree with you on this, I respect and understand your decision on this matter. I hope we can come up with a way to run code during init phase.

**Comment by mnapoli** [comment]
@matthewsuan OK I think you should read a bit more about Bref…

We are talking about the PHP-FPM layer here. The one made for people to do PHP like they used to on any server.

Now if you want to talk about pure Lambda-style code, then yes, it's possible. That's what the function layer is for. But if you are asking about doing this, that means that you probably should read more about this layer, because AFAIK all the information you need is in the documentation already.

So to sum up:

- if you want the convenience of FPM and a PHP environment that is familiar, with an easy integration with your favorite framework, then you can't do exotic/lambda-specific stuff
- if you want to do lambda-specific stuff, then you have to get out of the cosy environment provided by FPM and deal with the function runtime ("Bref for functions"), with all of the limitations that come with it

I'm sorry if you sense a bit of frustration here, but I'm trying to be helpful, providing some solutions and investing time in this discussion, and I feel like it's not going anywhere.

**Comment by matthewsuan** [comment]
@mnapoli apologies for generalizing bref. I was talking about bref-fpm (not bref in general) being unable to allow user to run init code - which I think is an important feature. 

So what's your initial thoughts on implementing init phase in fpm? or are you leaning towards not doing it in fpm?

Thank you.

**Comment by allan-simon** [comment]
I ended up doing this using KMS

I modified bin/console and public/index.php and it works like a charm , I certainly should use some kind of cache to avoid the KMS call everytime though

```php
<?php

use App\Kernel;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\ErrorHandler\Debug;
use Symfony\Component\HttpFoundation\Request;

require dirname(__DIR__).'/vendor/autoload.php';

////////////// start of modification ////////////////////


$dotEnv = new Dotenv();
$dotEnv->bootEnv(dirname(__DIR__).'/.env');


// used when deploying with Lambda
// so that nowhere in the CI/CD infrastructure
// the env variables are manipulated in clear text
if ($_SERVER['KMS_ENV_LOCAL'] ?? false) {

    $kmsClient = new \Aws\Kms\KmsClient([
        'version' => '2014-11-01',
        'region' => 'eu-west-3'
    ]);

    $ciphertext = base64_decode($_SERVER['KMS_ENV_LOCAL']);

    $result = $kmsClient->decrypt([
        'CiphertextBlob' => $ciphertext,
    ]);
    $plaintext = $result['Plaintext'];

    $values = $dotEnv->parse($plaintext);
    $dotEnv->populate($values, overrideExistingVars: true);
}
////////////// end of modification ////////////////////

if ($_SERVER['APP_DEBUG']) {
    umask(0000);

    Debug::enable();
}

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$request = Request::createFromGlobals();

// without these, (especially X_FORWATED_PROTO) symfony would not see
// the https from let's say ngrok, and will always generate http
// url instead of URL
$request->setTrustedProxies(
    ['192.0.0.1', 'REMOTE_ADDR'],
    // trust *all* "X-Forwarded-*" headers
    Request::HEADER_X_FORWARDED_FOR | Request::HEADER_X_FORWARDED_HOST | Request::HEADER_X_FORWARDED_PORT | Request::HEADER_X_FORWARDED_PROTO
);
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
```


and for bin/console 

```patch
-(new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
+$dotEnv = new Dotenv();
+$dotEnv->bootEnv(dirname(__DIR__).'/.env');
+
+// used when deploying with Lambda
+// so that nowhere in the CI/CD infrastructure
+// the env variables are manipulated in clear text
+if ($_SERVER['KMS_ENV_LOCAL'] ?? false) {
+
+    $kmsClient = new \Aws\Kms\KmsClient([
+        'version' => '2014-11-01',
+        'region' => 'eu-west-3'
+    ]);
+
+    $ciphertext = base64_decode($_SERVER['KMS_ENV_LOCAL']);
+
+    $result = $kmsClient->decrypt([
+        'CiphertextBlob' => $ciphertext,
+    ]);
+    $plaintext = $result['Plaintext'];
+
+    $values = $dotEnv->parse($plaintext);
+    $dotEnv->populate($values, overrideExistingVars: true);
+}
 
````

**Comment by shouze** [comment]
@allan-simon please notice that if you use async-aws Symfony bundle [everything works transparently](https://github.com/async-aws/aws/blob/master/src/Integration/Symfony/Bundle/src/Secrets/SsmVault.php). It's even cached after a cold start.

**Comment by deleugpn** [comment]
Closing this for now. Here's my thoughts on this: https://github.com/brefphp/bref/pull/982#issuecomment-894690099

If anyone have any more to add feel free to open a new discussion/issue.

**Comment by mnapoli** [comment]
I'm revisiting this issue after all this time, here is a possible PR: https://github.com/brefphp/bref/pull/1376
